 const times = [
  { id: 1, nome: 'Flamengo', emblema: '/assets/fla.png', sigla: 'FLA' },
  { id: 2, nome: 'Fluminense', emblema: '/assets/flu.png', sigla: 'FLU' },
  { id: 3, nome: 'Botafogo', emblema: '/assets/bot.png', sigla: 'BOT' },
  { id: 4, nome: 'Palmeiras', emblema: '/assets/pal.png', sigla: 'PAL' },
  { id: 5, nome: 'Santos', emblema: '/assets/san.png', sigla: 'SAN' },
  { id: 6, nome: 'São Paulo', emblema: '/assets/sao.png', sigla: 'SAO' },
  { id: 7, nome: 'Corinthians', emblema: '/assets/cor.png', sigla: 'COR' },
  { id: 8, nome: 'Grêmio', emblema: '/assets/gre.png', sigla: 'GRE' },
  { id: 9, nome: 'Internacional', emblema: '/assets/int.png', sigla: 'INT' },
  { id: 10, nome: 'Atlético Mineiro', emblema: '/assets/cam.png', sigla: 'CAM' },
  { id: 11, nome: 'Cruzeiro', emblema: '/assets/cru.png', sigla: 'CRU' },
  { id: 12, nome: 'Bahia', emblema: '/assets/bai.png', sigla: 'BAH' },
  { id: 13, nome: 'Sport', emblema: '/assets/spt.png', sigla: 'SPT' },
  { id: 14, nome: 'Vasco', emblema: '/assets/vas.png', sigla: 'VAS' },
  { id: 15, nome: 'Fortaleza', emblema: '/assets/for.png', sigla: 'FOR' },
  { id: 16, nome: 'Ceará', emblema: '/assets/cea.png', sigla: 'CEA' },
  { id: 17, nome: 'Vitória', emblema: '/assets/vit.png', sigla: 'VIT' },
  { id: 18, nome: 'Mirassol', emblema: '/assets/mir.png', sigla: 'MIR' },
  { id: 19, nome: 'Red Bull Bragantino', emblema: '/assets/rbb.png', sigla: 'RBB' },
  { id: 20, nome: 'Juventude', emblema: '/assets/juv.png', sigla: 'JUV' }
];
